import express from 'express';
import { etsyRequest, getShopId } from './etsy.js';
const router=express.Router();
const clamp=(n,a,b)=>Math.max(a,Math.min(b,n));
function listingId(v){const id=String(v||'').trim();if(!/^\d+$/.test(id)){const e=new Error('Invalid listingId');e.status=400;throw e;}return id;}
function rankOf(x){return Number(x?.rank??x?.listing_image_rank??9999);}
function imageUrl(x){return x?.url_fullxfull||x?.url_300x300||x?.url_570xN||null;}
function audit(listing,rows){rows=[...rows].sort((a,b)=>rankOf(a)-rankOf(b));const first=rows[0]||null;const count=rows.length;let score=100;const issues=[];if(!first||!imageUrl(first)){score-=55;issues.push('rank_1_missing');}if(count<5){score-=25;issues.push('too_few_images');}else if(count<8){score-=12;issues.push('image_set_thin');}const w=Number(first?.full_width||0),h=Number(first?.full_height||0);if(w&&h&&Math.min(w,h)<2000){score-=15;issues.push('rank_1_resolution_under_2000');}score=clamp(score,0,100);return{listing_id:String(listing?.listing_id||''),title:listing?.title||'',image_count:count,thumbnail_score:score,status:score>=90?'strong':score>=75?'review':'needs_change',issues,source_locked:Boolean(first&&imageUrl(first)),source_artwork:first?{listing_image_id:first.listing_image_id,rank:rankOf(first),url:imageUrl(first),width:first.full_width||null,height:first.full_height||null}:null};}
router.get('/listings/:listingId/source',async(req,res,next)=>{try{const id=listingId(req.params.listingId);const[listing,images]=await Promise.all([etsyRequest('/listings/'+id),etsyRequest('/listings/'+id+'/images')]);const a=audit(listing,Array.isArray(images?.results)?images.results:[]);if(!a.source_locked)return res.status(409).json({error:'rank_1_artwork_unavailable',generation_allowed:false,etsy_modified:false});res.json({ok:true,...a,source_rule:'ETSY_LISTING_RANK_1',generation_allowed:true,etsy_modified:false});}catch(e){next(e);}});
router.post('/scan',async(req,res,next)=>{try{const shop=await getShopId();const max=clamp(Number(req.body?.listingLimit||500),1,500);let offset=0,listings=[];while(listings.length<max){const page=await etsyRequest('/shops/'+shop+'/listings',{params:{state:'active',limit:100,offset}});const r=Array.isArray(page?.results)?page.results:[];listings.push(...r);if(r.length<100)break;offset+=r.length;}listings=listings.slice(0,max);const results=[];for(const l of listings){try{const im=await etsyRequest('/listings/'+l.listing_id+'/images');results.push(audit(l,Array.isArray(im?.results)?im.results:[]));}catch(e){results.push({listing_id:String(l.listing_id),title:l.title||'',thumbnail_score:0,status:'needs_change',issues:['image_audit_failed'],source_locked:false});}}const needs=results.filter(x=>x.status==='needs_change').length,review=results.filter(x=>x.status==='review').length;res.json({ok:true,total_count:results.length,needs_change_count:needs,review_count:review,strong_count:results.length-needs-review,results:results.sort((a,b)=>a.thumbnail_score-b.thumbnail_score),read_only:true,etsy_modified:false});}catch(e){next(e);}});
router.post('/jobs/prepare',async(req,res,next)=>{try{const id=listingId(req.body?.listingId),preset=String(req.body?.preset||'floor_large');const images=await etsyRequest('/listings/'+id+'/images');const rows=Array.isArray(images?.results)?images.results:[];rows.sort((a,b)=>rankOf(a)-rankOf(b));const source=rows[0],url=imageUrl(source);if(!source||!url)return res.status(409).json({error:'rank_1_artwork_unavailable',generation_allowed:false,etsy_modified:false});res.json({ok:true,preview_only:true,listing_id:id,preset,source_locked:true,source_rule:'ETSY_LISTING_RANK_1',source_artwork:{listing_image_id:source.listing_image_id,rank:rankOf(source),url},generation_contract:{preserve_artwork_exactly:true,allow_redraw:false,allow_recolor:false,allow_crop:false,allow_stretch:false,primary_presets:['floor_large','wall_large'],minimum_short_side_px:2000},provider_connected:false,generation_allowed:false,next_required:'generation_provider',etsy_modified:false});}catch(e){next(e);}});
export default router;